### ISSUE TITLE
Feature request #2

### ISSUE THREAD

**Issue by gregdeichler** [BIG-RAT/userAssign#3]
We have a custom extension attribute called "Image Configuration". Would it be possible to create a popup menu that has the selections available in the image configuration extension attribute? This would allow this app to be a one stop solution for inventory and configuration.

I know how to do it in a bash script / command line but not in swift.

curl -H "Accept: text/xml" -sfku APIUSER:XXXXXXXXXX https://XXXXXX.jamfcloud.com/JSSResource/computerextensionattributes/id/9 | xpath '/computer_extension_attribute/input_type/popup_choices' 2>/dev/null | xmllint --format - | awk -F'>|<' '/<choice>/{print $3}'

Thanks again, and this will be the last request :-)

**Comment by BIG-RAT** [comment]
Possible. To be clear are you looking for options from a mobile device EA?

**Comment by gregdeichler** [comment]
Yessir. I would love the option to set an Extension attribute for a mobile device.

**Comment by BIG-RAT** [comment]
Updated.  Hope it's what you were looking for.  Need to hit some other projects.

**Comment by gregdeichler** [comment]
Looks perfect. Ill be testing later today. Thank you for your work on this much needed app.
