### ISSUE TITLE
tvOS port...

### ISSUE THREAD

**Issue by gregdeichler** [BIG-RAT/userAssign#4]
This app works perfectly with our iOS devices. Is there any chance of a tvOS port of this app?

Thanks for all the great tools.

**Comment by BIG-RAT** [comment]
Might be a while before I can get to this.  Have you tried changing the Architecture to tvOS, then build?
<img width="958" alt="Screen Shot 2021-11-17 at 9 45 50 AM" src="https://user-images.githubusercontent.com/22251543/142245949-49c5f06c-d34b-48a6-9c0f-08369a91497c.png">

**Comment by gregdeichler** [comment]
No. It gives a storyboard error. All good. I figured it was worth asking.
